export default function Home() {
  return (
    <>
      <div>
        <title>Moe Sarraf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
      <main className={` bg-gray-200 px-10 md:px-20 lg:px-40`}>
        <section className="min-h-screen">
          <nav className={`mb-12 flex justify-between py-10`}>
            <h1 className={`text-xl`}>Lilglu4e</h1>
          </nav>
          <div className="p-10 text-center">
            <h2
              className={`py-2 text-5xl font-medium text-teal-600 md:text-6xl dark:text-teal-400`}
            >
              Moe Sarraf
            </h2>
            <h3 className={`py-2 text-2xl md:text-3xl`}>
              Developer and designer.
            </h3>
            <p
              className={`mx-auto max-w-xl py-5 text-sm leading-8 text-gray-800 md:text-xl`}
            >
              {`As a Computer Science student deeply engaged with Data Science, AI, and Full-Stack Development, I am driven by a passion to blend creativity and technology. My portfolio, featuring diverse projects such as an interactive React mini-game and an innovative NBA MVP prediction model, is a testament to my commitment to crafting engaging user experiences and leveraging the power of data-driven insights.`}
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
